# Site settings
title: FaxIt
description: 'Send fax anywhere and pay with Mobile Money , Just like that !'
url: 'http://www.faxit.cm' 
baseurl: '/'
google_analytics: 'xxxxxxxxx'

author:
  name: 'FaxIt'
  email: contact@faxit.cm
  twitter_username: faxit
  

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'src']
